# Generated by Django 4.2.7 on 2025-12-30 09:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_product_estimateheader_estimatedetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("wood_species", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("location", models.TextField(blank=True, null=True)),
                ("people", models.JSONField(blank=True, default=list)),
                (
                    "carpenter_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estimate_header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_cards",
                        to="organizations.estimateheader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Card",
                "verbose_name_plural": "Job Cards",
                "db_table": "job_cards",
                "ordering": ["-created_at"],
            },
        ),
    ]
