# Generated by Django 4.2.7 on 2025-12-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_jobcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcard",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product associated with this job card",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_cards",
                to="organizations.product",
            ),
        ),
    ]
